# Generated by Django 3.1 on 2023-10-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picProcess', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='title',
        ),
        migrations.AddField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_images/'),
        ),
    ]
