# Generated by Django 3.1 on 2023-10-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picProcess', '0002_auto_20231015_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='processed_image',
            field=models.ImageField(blank=True, null=True, upload_to='processed_images'),
        ),
    ]
