# Generated by Django 3.1 on 2023-10-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('picProcess', '0003_auto_20231017_0111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='photo',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='processed_image',
        ),
    ]
