# Generated by Django 3.1 on 2023-10-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='用户编号')),
                ('username', models.CharField(max_length=30, verbose_name='用户名称')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('status', models.CharField(max_length=1, verbose_name='权限')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='注册日期')),
            ],
            options={
                'verbose_name': '用户信息表',
                'db_table': 'UserInfo',
            },
        ),
    ]
